https://stackoverflow.com/questions/30015090/manage-multiple-following-positional-argument-with-argparse
https://kipalog.com/posts/Tao-mot-CLI-app-don-gian-voi-Python
https://stackoverflow.com/questions/3204782/how-to-check-if-a-file-is-a-directory-or-regular-file-in-python
https://stackoverflow.com/questions/5137497/find-current-directory-and-files-directory
https://stackoverflow.com/questions/4028904/how-to-get-the-home-directory-in-python
https://stackoverflow.com/questions/11068419/check-if-file-is-symlink-in-python
https://gist.github.com/simonw/229186
https://pymotw.com/2/difflib/
https://stackoverflow.com/questions/15039528/what-is-the-difference-between-os-open-and-os-fdopen-in-python
https://docs.python.org/3/library/os.html#os.open
http://book.pythontips.com/en/latest/args_and_kwargs.html
https://www.pythonforbeginners.com/system/python-sys-argv
http://www.giaithuatlaptrinh.com/?p=78
http://www.giaithuatlaptrinh.com/?p=99
http://www.giaithuatlaptrinh.com/?tag=longest-common-subsequence
https://www.geeksforgeeks.org/python-program-for-longest-common-subsequence/
https://www.geeksforgeeks.org/python-program-for-longest-common-subsequence/
https://stackoverflow.com/questions/2104080/how-to-check-file-size-in-python
https://serverfault.com/questions/211005/rsync-difference-between-checksum-and-ignore-times-options
https://www.tutorialspoint.com/python/os_stat.htm
